### ISSUE TITLE
Sync with AML team for extensibility feedback

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/bicep-extensibility#16]
* What needs to be addressed for public preview?
* What should we address for beyond public preview?
* Any other suggestions/feedback.

**Comment by alex-frankel** [comment]
I'm going to close this one as complete. Per Stan's feedback, the main blocker is an optimized workflow for converting YAML manifests to bicep. Stan submitted a PR for a decompile tool for this, which would address the feedback. Stan's team does not have bandwidth to work on the `includeYamlContent()` function.
